### ISSUE TITLE
lyric custom comp.

### ISSUE THREAD

**Issue by MPopti0n** [arsaboo/homeassistant-config#6]
When you create the API app on the honeywell lyric api site.. what is the callback URL to use?
I configure it in HA (request token) and it was a success (I can see the token / refresh toket / exp. date/time in the file), but I don't see any of my sesors (2x water leak detector) on the board even after a restart of HA.

The HA log file look like that :

```
2018-02-27 01:58:52 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform lyric
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 84, in async_setup
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climate/lyric.py", line 91, in setup_platform
    schema=RESUME_PROGRAM_SCHEMA)
TypeError: register() got multiple values for argument 'schema'
```

Running HA on rpi 3

// BTW, great stuff! Tks!

**Comment by arsaboo** [comment]
Thanks for the kind words. Looks like you have not updated the lyric files. Please see the discussion [here](https://community.home-assistant.io/t/honeywell-lyric-thermostat/3520/334?u=arsaboo) for the same error.

**Comment by MPopti0n** [comment]
Updated the code! Tks

And what's the callback URL to use on the Honeywell side when I create the "app"?

**Comment by arsaboo** [comment]
I did this a while back, but I think that is something like `https://yourhomeassistant:8123/api/lyric/authenticate`.
